### PR TITLE
Add Ruby 1.8.7 compatibility

### PR DESCRIPTION
**Pull request by sferik**
I’m interested in using `adamantium` in the `twitter` gem, however, this will require Ruby 1.8.7 support, at least for the next 6 months. I am happy to do all the maintenance work myself. I’m also okay with Ruby 1.8.7 support being dropped when version 1.0.0 is released, just as we’re doing with `equalizer` and `memoizable`.

### CODE REVIEW

**Comment by mbj** [comment]
@sferik Can we merge this in a `18support` branch to release from there. So we dont have to patch it out again?

**Comment by sferik** [comment]
Never mind. There seems to be an incompatibility with `ice_nine` that’s causing the tests to fail on Ruby 1.8.7.

I can wait 6 months to release the next version of `twitter`, which will only support Ruby 1.9.3 and greater.

**Comment by mbj** [comment]
> I can wait 6 months to release the next version of twitter, which will only support Ruby 1.9.3 and greater.

Nice!

**Comment by sferik** [comment]
@mbj By the way, I took [your advice](https://github.com/rom-rb/devtools/pull/47#issuecomment-30082149) and benchmarked `Adamantium` vs. `Adamantium::Flat` vs. nothing and found `Adamantium::Flat` to be only marginally slower than nothing, so I will definitely be depending on `adamantium` in the next major version of the `twitter` gem.

**Comment by mbj** [comment]
@sferik That is interesting. I never took a look on your twitter gem and its internals. I just assumed it does deep freeze deeply nested hash/array trees, those that typically get returned when parsing JSON responses. In this scenario I got a significant speedup with NOT deep freezing those datastructures.

**Pull request closed without merging**
